CREATE TABLE IF NOT EXISTS "favouriteLocation" (
    "email" TEXT,
    "loc_name" TEXT
);
INSERT INTO "favouriteLocation" VALUES
    ('sseargeant0@virginia.edu','Leroy'),
    ('mcowhig1@google.de','Iowa'),
    ('fjanes2@discovery.com','Jenifer'),
    ('challer3@tamu.edu','Stang'),
    ('ajanik4@hud.gov','Red Cloud'),
    ('jnewlove5@yellowbook.com','Autumn Leaf'),
    ('gwinterborne6@reddit.com','Fordem'),
    ('gphlippsen7@gizmodo.com','1st'),
    ('jeirwin8@seesaa.net','Hauk'),
    ('iprendeguest9@t-online.de','Laurel'),
    ('smarteleta@ed.gov','Twin Pines'),
    ('bhaithb@imdb.com','Stone Corner'),
    ('mcallendarc@reverbnation.com','Glacier Hill'),
    ('fdelasalled@ameblo.jp','Muir'),
    ('nsodore@mapy.cz','Rowland'),
    ('ebinnallf@devhub.com','Westerfield'),
    ('kborrisg@ask.com','Porter'),
    ('scastellsh@salon.com','Independence'),
    ('cokendeni@irs.gov','Dovetail'),
    ('rwarehamj@woothemes.com','Killdeer'),
    ('ndobesonk@about.me','Arapahoe'),
    ('ckelwickl@addtoany.com','Sycamore'),
    ('jhyronsm@microsoft.com','Westend'),
    ('sbickerstethn@yelp.com','Golf View'),
    ('irubinowitcho@princeton.edu','Wayridge'),
    ('swatsamp@netscape.com','Debra'),
    ('ipatientq@homestead.com','Sycamore'),
    ('dmorenar@domainmarket.com','South'),
    ('fburnapps@archive.org','Oxford'),
    ('fbuttwellt@stanford.edu','Norway Maple'),
    ('gfranklinu@toplist.cz','Troy'),
    ('epauletv@csmonitor.com','Scofield'),
    ('fblacktinw@bandcamp.com','Beilfuss'),
    ('smilnthorpex@sfgate.com','Laurel'),
    ('mmarshlandy@typepad.com','Bobwhite'),
    ('hcorryz@webnode.com','Jackson'),
    ('ahaddeston10@ebay.com','Elmside'),
    ('dduchateau11@delicious.com','Maple'),
    ('smeardon12@nyu.edu','Tennyson'),
    ('sweldon13@nyu.edu','Springs'),
    ('gtoovey14@google.cn','Little Fleur'),
    ('vwawer15@altervista.org','Amoth'),
    ('mgobourn16@feedburner.com','Marcy'),
    ('dchaman17@wikispaces.com','Mendota'),
    ('aharsent18@newyorker.com','Comanche'),
    ('rgambell19@paginegialle.it','Old Shore'),
    ('jgamett1a@nytimes.com','Corry'),
    ('hbocock1b@state.gov','Mitchell'),
    ('rpennone1c@mapquest.com','Washington');
