CREATE TABLE IF NOT EXISTS "Likes" (
    "email" TEXT,
    "name" TEXT
);
INSERT INTO "likes" VALUES
    ('sseargeant0@virginia.edu','Hatity'),
    ('mcowhig1@google.de','Cardify'),
    ('fjanes2@discovery.com','Andalax'),
    ('challer3@tamu.edu','Stronghold'),
    ('ajanik4@hud.gov','Lotstring'),
    ('jnewlove5@yellowbook.com','Lotstring'),
    ('gwinterborne6@reddit.com','Home Ing'),
    ('gphlippsen7@gizmodo.com','Job'),
    ('jeirwin8@seesaa.net','Aerified'),
    ('iprendeguest9@t-online.de','Treeflex'),
    ('smarteleta@ed.gov','Bytecard'),
    ('bhaithb@imdb.com','Fix San'),
    ('mcallendarc@reverbnation.com','Span'),
    ('fdelasalled@ameblo.jp','Zontrax'),
    ('nsodore@mapy.cz','Konklux'),
    ('ebinnallf@devhub.com','Greenlam'),
    ('kborrisg@ask.com','Bigtax'),
    ('scastellsh@salon.com','Solarbreeze'),
    ('cokendeni@irs.gov','Toughjoyfax'),
    ('rwarehamj@woothemes.com','Otcom'),
    ('ndobesonk@about.me','Opela'),
    ('ckelwickl@addtoany.com','Bitwolf'),
    ('jhyronsm@microsoft.com','Zamit'),
    ('sbickerstethn@yelp.com','Tres-Zap'),
    ('irubinowitcho@princeton.edu','Otcom'),
    ('swatsamp@netscape.com','Ventosanzap'),
    ('ipatientq@homestead.com','Pannier'),
    ('dmorenar@domainmarket.com','Sonair'),
    ('fburnapps@archive.org','Ventosanzap'),
    ('fbuttwellt@stanford.edu','Namfix');
