CREATE TABLE IF NOT EXISTS "Songs" (
    "name" TEXT,
    "duration" INT,
    "artist" TEXT
);
INSERT INTO "songs" VALUES
    ('Hatity',1,'Isis'),
    ('Cardify',2,'Pennie'),
    ('Andalax',3,'Melli'),
    ('Stronghold',4,'Yuma'),
    ('Lotstring',5,'Papageno'),
    ('Home Ing',7,'Emmett'),
    ('Job',8,'Florance'),
    ('Aerified',9,'Nedda'),
    ('Treeflex',10,'Kermie'),
    ('Bytecard',11,'Sander'),
    ('Fix San',12,'Tremain'),
    ('Span',13,'Dougy'),
    ('Zontrax',14,'Audrey'),
    ('Konklux',15,'Lazar'),
    ('Greenlam',16,'Lettie'),
    ('Bigtax',17,'Baldwin'),
    ('Solarbreeze',18,'Coleman'),
    ('Toughjoyfax',19,'Merrie'),
    ('Otcom',20,'Prudence'),
    ('Bitwolf',22,'Bernadina'),
    ('Zamit',23,'Clemente'),
    ('Tres-Zap',24,'Clemmy'),
    ('Ventosanzap',26,'Isidore'),
    ('Pannier',27,'Salomone'),
    ('Sonair',28,'Bellanca'),
    ('Ventosanzap',29,'Allix'),
    ('Namfix',30,'Friedrich'),
    ('Opela',54,'Ettie'),
    ('Prodder',31,'Prudence'),
    ('Tampflex',33,'Catlin'),
    ('Otcom',34,'Rochette'),
    ('Duobam',35,'Trescha'),
    ('Ronstring',37,'Melina'),
    ('Transcof',39,'Drake'),
    ('Bitchip',40,'Myriam'),
    ('Asoka',41,'Neddie'),
    ('Sonsing',42,'Ambur'),
    ('Holdlamis',43,'Kleon'),
    ('Zoolab',44,'Aarika'),
    ('Sonsing',45,'Nan'),
    ('Fix San',46,'Jany'),
    ('Flexidy',47,'Bellina'),
    ('Y-find',48,'Duane'),
    ('Bytecard',49,'Niels'),
    ('Sonsing',50,'Fremont'),
    ('Ventosanzap',51,'Britney'),
    ('Voyatouch',52,'Hedvig'),
    ('Mat Lam Tam',53,'Cece'),
    ('Redhold',55,'Gretta'),
    ('Ventosanzap',56,'Dasha'),
    ('Tampflex',57,'Hedwiga'),
    ('Pannier',58,'Christos'),
    ('Konklab',59,'Zenia'),
    ('Bytecard',60,'Dorothea'),
    ('Regrant',61,'Jandy'),
    ('Rank',62,'Jamaal'),
    ('It',63,'Amye'),
    ('Span',64,'Tyrone'),
    ('Vagram',65,'Orbadiah'),
    ('Tampflex',67,'Ki'),
    ('Wrapsafe',68,'Rheta'),
    ('Viva',69,'Shaw'),
    ('Keylex',70,'Hedy'),
    ('Trippledex',71,'Germaine'),
    ('Cookley',72,'Shanna'),
    ('Transcof',73,'Ibbie'),
    ('Home Ing',74,'Chev'),
    ('Transcof',75,'Catharina'),
    ('Latlux',76,'Monika'),
    ('Keylex',77,'Mill'),
    ('Gembucket',78,'Robena'),
    ('Matsoft',79,'Gaby'),
    ('Tresom',80,'Ettie'),
    ('Overhold',81,'Alex'),
    ('Gembucket',82,'Kamilah'),
    ('It',84,'Riva'),
    ('Sonair',85,'Winifield'),
    ('Subin',86,'Bentley'),
    ('Alpha',87,'Audi'),
    ('Veribet',88,'Colene'),
    ('Otcom',89,'Maddy'),
    ('Home Ing',90,'Mei'),
    ('Tampflex',91,'Desi'),
    ('Pannier',92,'Broddy'),
    ('Gembucket',93,'Berke'),
    ('Stringtough',94,'Genevieve'),
    ('Andalax',95,'Dawn'),
    ('Matsoft',96,'Adeline'),
    ('Tres-Zap',97,'Maxwell'),
    ('Subin',98,'Delainey'),
    ('Holdlamis',99,'Deina'),
    ('Bitchip',100,'Marcelline'),
    ('Overhold',101,'Pier');
